name: deploy
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: test
        run: npm run test
      - name: report
        env:
          COVERALLS_REPO_TOKEN: ${{ coverage.COVERALLS_REPO_TOKEN }}
        run: npm run coverage

